export enum ValidationErrorCode {
  INVALID_FIELD = 'INVALID_FIELD',
  INVALID_EMAIL = 'INVALID_EMAIL',
  INVALID_ID = 'INVALID_ID',

  NOT_STRING = 'NOT_STRING',
  STRING_TOO_SHORT = 'STRING_TOO_SHORT',
  STRING_TOO_LONG = 'STRING_TOO_LONG',

  NOT_ARRAY = 'NOT_ARRAY',
  ARRAY_TOO_SHORT = 'ARRAY_TOO_SHORT',
  ARRAY_TOO_LONG = 'ARRAY_TOO_LONG',

  FILE_TOO_BIG = 'FILE_TOO_BIG',
  INVALID_FILE_TYPE = 'INVALID_FILE_TYPE',
  FILE_IS_REQUIRED = 'FILE_IS_REQUIRED',
  UNEXPECTED_FILE = 'UNEXPECTED_FILE',

  NOT_NUMBER = 'NOT_NUMBER',
  NUMBER_TOO_SMALL = 'NUMBER_TOO_SMALL',
  NUMBER_TOO_BIG = 'NUMBER_TOO_BIG',
}
