export enum AppErrorCode {
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
  NOT_FOUND = 'NOT_FOUND',
  VALIDATION_ERROR = 'VALIDATION_ERROR',

  IMAGE_ALREADY_EXISTS = 'IMAGE_ALREADY_EXISTS',
  NO_IMAGE = 'NO_IMAGE',

  SUPERPOWER_ALREADY_EXISTS = 'SUPERPOWER_ALREADY_EXISTS',
  INVALID_SUPERPOWER = 'INVALID_SUPERPOWER',
  NO_SUPERPOWERS = 'NO_SUPERPOWERS',
  SUPERPOWER_NOT_FOUND = 'SUPERPOWER_NOT_FOUND',

  SUPERHERO_ALREADY_EXISTS = 'SUPERHERO_ALREADY_EXISTS',
  SUPERHERO_NOT_FOUND = 'SUPERHERO_NOT_FOUND',
}
